version: "3"

services:
  nextjs:
    container_name: nextjs
    build:
      context: .. # root of the project
      dockerfile: docker/next/Dockerfile
    env_file:
      - ../.env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: mongodb
    image: mongo
    restart: always
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
